module.exports = class Data1777395466361 {
    name = 'Data1777395466361'

    async up(db) {
        await db.query(`CREATE TABLE "post_victim" ("id" character varying NOT NULL, "created_at_block" integer NOT NULL, "post_id" character varying, "address_id" character varying, CONSTRAINT "PK_a91e426ba6050e975aa9a6da553" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_3927e367646ef7912bdbb1c3e9" ON "post_victim" ("post_id") `)
        await db.query(`CREATE INDEX "IDX_7a79ba88f0a3c03101af02e3ad" ON "post_victim" ("address_id") `)
        await db.query(`CREATE TABLE "address" ("id" character varying NOT NULL, "attacker_score" numeric NOT NULL, "attacker_appearances" integer NOT NULL, "is_victim" boolean NOT NULL, "victim_active_post_count" integer NOT NULL, CONSTRAINT "PK_d92de1f82754668b5f5f5dd4fd5" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "post_attacker" ("id" character varying NOT NULL, "created_at_block" integer NOT NULL, "post_id" character varying, "address_id" character varying, CONSTRAINT "PK_974ac875837992cfb98077d34ad" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_ef8456d34ecfba26db11b5f924" ON "post_attacker" ("post_id") `)
        await db.query(`CREATE INDEX "IDX_91d06e958d1a8e2a068b22248d" ON "post_attacker" ("address_id") `)
        await db.query(`CREATE TABLE "confirmation" ("id" character varying NOT NULL, "old_direction" character varying(4) NOT NULL, "new_direction" character varying(4) NOT NULL, "block_number" integer NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "tx_hash" text NOT NULL, "post_id" character varying, "confirmer_id" character varying, CONSTRAINT "PK_3eee17867bc79b59e68f5f879fe" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_492dff0fa2bc07c4387b77a1db" ON "confirmation" ("post_id") `)
        await db.query(`CREATE INDEX "IDX_b1ae2d0af9fa9a2257869c5fd3" ON "confirmation" ("confirmer_id") `)
        await db.query(`CREATE TABLE "edit" ("id" character varying NOT NULL, "kind" character varying(12) NOT NULL, "new_note" text, "new_title" text, "added_attackers" text array, "added_victims" text array, "block_number" integer NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "tx_hash" text NOT NULL, "post_id" character varying, CONSTRAINT "PK_062a4b68154c101205e4595810d" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_8d773843cb3e251862f8a62f9a" ON "edit" ("post_id") `)
        await db.query(`CREATE TABLE "post" ("id" character varying NOT NULL, "attacked_at" TIMESTAMP WITH TIME ZONE NOT NULL, "last_updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "title" text NOT NULL, "note" text NOT NULL, "confirmations" integer NOT NULL, "disconfirmations" integer NOT NULL, "net_score" integer NOT NULL, "removed" boolean NOT NULL, "created_at_block" integer NOT NULL, "created_at_timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "removed_at_block" integer, "removed_at_timestamp" TIMESTAMP WITH TIME ZONE, "poster_id" character varying, CONSTRAINT "PK_be5fda3aac270b134ff9c21cdee" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_9a9e362dbd95ed3d070776e436" ON "post" ("poster_id") `)
        await db.query(`CREATE TABLE "whitelist_change" ("id" character varying NOT NULL, "added" boolean NOT NULL, "block_number" integer NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "tx_hash" text NOT NULL, "addr_id" character varying, CONSTRAINT "PK_c3394ea7514bb4a21b8ca6e13f7" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_d2b535d850a99527c8e73489e7" ON "whitelist_change" ("addr_id") `)
        await db.query(`CREATE TABLE "whitelister" ("id" character varying NOT NULL, "is_currently_whitelisted" boolean NOT NULL, "first_whitelisted_at" TIMESTAMP WITH TIME ZONE, "first_whitelisted_at_block" integer, "last_changed_at" TIMESTAMP WITH TIME ZONE, "last_changed_at_block" integer, CONSTRAINT "PK_f50124ac93478d0ad3ab4f0e6f0" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "proposer" ("id" character varying NOT NULL, "post_count" integer NOT NULL, "total_confirmations" numeric NOT NULL, "total_disconfirmations" numeric NOT NULL, "first_posted_at" TIMESTAMP WITH TIME ZONE, "first_posted_at_block" integer, "last_updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "last_updated_at_block" integer NOT NULL, CONSTRAINT "PK_4864e2acee4223120fcbdc75f29" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "upgrade" ("id" character varying NOT NULL, "new_implementation" text NOT NULL, "block_number" integer NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "tx_hash" text NOT NULL, CONSTRAINT "PK_855aca5df3eceff6e4fe49245c4" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "ownership_change" ("id" character varying NOT NULL, "previous_owner" text NOT NULL, "new_owner" text NOT NULL, "block_number" integer NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "tx_hash" text NOT NULL, CONSTRAINT "PK_6f6160b33237be687c69c50015d" PRIMARY KEY ("id"))`)
        await db.query(`ALTER TABLE "post_victim" ADD CONSTRAINT "FK_3927e367646ef7912bdbb1c3e95" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "post_victim" ADD CONSTRAINT "FK_7a79ba88f0a3c03101af02e3ad5" FOREIGN KEY ("address_id") REFERENCES "address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "post_attacker" ADD CONSTRAINT "FK_ef8456d34ecfba26db11b5f9243" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "post_attacker" ADD CONSTRAINT "FK_91d06e958d1a8e2a068b22248d5" FOREIGN KEY ("address_id") REFERENCES "address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "confirmation" ADD CONSTRAINT "FK_492dff0fa2bc07c4387b77a1db0" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "confirmation" ADD CONSTRAINT "FK_b1ae2d0af9fa9a2257869c5fd3f" FOREIGN KEY ("confirmer_id") REFERENCES "whitelister"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "edit" ADD CONSTRAINT "FK_8d773843cb3e251862f8a62f9ae" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "post" ADD CONSTRAINT "FK_9a9e362dbd95ed3d070776e436c" FOREIGN KEY ("poster_id") REFERENCES "whitelister"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "whitelist_change" ADD CONSTRAINT "FK_d2b535d850a99527c8e73489e73" FOREIGN KEY ("addr_id") REFERENCES "whitelister"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`ALTER TABLE "whitelist_change" DROP CONSTRAINT "FK_d2b535d850a99527c8e73489e73"`)
        await db.query(`ALTER TABLE "post" DROP CONSTRAINT "FK_9a9e362dbd95ed3d070776e436c"`)
        await db.query(`ALTER TABLE "edit" DROP CONSTRAINT "FK_8d773843cb3e251862f8a62f9ae"`)
        await db.query(`ALTER TABLE "confirmation" DROP CONSTRAINT "FK_b1ae2d0af9fa9a2257869c5fd3f"`)
        await db.query(`ALTER TABLE "confirmation" DROP CONSTRAINT "FK_492dff0fa2bc07c4387b77a1db0"`)
        await db.query(`ALTER TABLE "post_attacker" DROP CONSTRAINT "FK_91d06e958d1a8e2a068b22248d5"`)
        await db.query(`ALTER TABLE "post_attacker" DROP CONSTRAINT "FK_ef8456d34ecfba26db11b5f9243"`)
        await db.query(`ALTER TABLE "post_victim" DROP CONSTRAINT "FK_7a79ba88f0a3c03101af02e3ad5"`)
        await db.query(`ALTER TABLE "post_victim" DROP CONSTRAINT "FK_3927e367646ef7912bdbb1c3e95"`)
        await db.query(`DROP TABLE "ownership_change"`)
        await db.query(`DROP TABLE "upgrade"`)
        await db.query(`DROP TABLE "proposer"`)
        await db.query(`DROP TABLE "whitelister"`)
        await db.query(`DROP INDEX "public"."IDX_d2b535d850a99527c8e73489e7"`)
        await db.query(`DROP TABLE "whitelist_change"`)
        await db.query(`DROP INDEX "public"."IDX_9a9e362dbd95ed3d070776e436"`)
        await db.query(`DROP TABLE "post"`)
        await db.query(`DROP INDEX "public"."IDX_8d773843cb3e251862f8a62f9a"`)
        await db.query(`DROP TABLE "edit"`)
        await db.query(`DROP INDEX "public"."IDX_b1ae2d0af9fa9a2257869c5fd3"`)
        await db.query(`DROP INDEX "public"."IDX_492dff0fa2bc07c4387b77a1db"`)
        await db.query(`DROP TABLE "confirmation"`)
        await db.query(`DROP INDEX "public"."IDX_91d06e958d1a8e2a068b22248d"`)
        await db.query(`DROP INDEX "public"."IDX_ef8456d34ecfba26db11b5f924"`)
        await db.query(`DROP TABLE "post_attacker"`)
        await db.query(`DROP TABLE "address"`)
        await db.query(`DROP INDEX "public"."IDX_7a79ba88f0a3c03101af02e3ad"`)
        await db.query(`DROP INDEX "public"."IDX_3927e367646ef7912bdbb1c3e9"`)
        await db.query(`DROP TABLE "post_victim"`)
    }
}
